#!/bin/bash

cd filebenches

RESULTS=../results/$FS/filebench
mkdir -p $RESULTS

TSET=( 18 1 )
REPS=10

sudo sh -c 'echo 0 > /proc/sys/kernel/randomize_va_space'

for f in *.f; do
	# These workloads are wobly with Bento, so
	cd ..
	./umount
	./prepare_disk
	./mount
	cd filebenches

	sed -i -e "s#set \$dir=.*#set \$dir=$MNT#g" $f
	echo "Running $f"
	mkdir -p $RESULTS/$f

	if echo $f | grep "1t"; then
		for T in "${TSET[@]}"; do
			sed -i -e "s#set \$nthreads=.*#set \$nthreads=$T#g" $f

			WREPS=$REPS
			if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
				WREPS=1
			fi
			for i in $(seq 1 $WREPS); do
				echo "i=$i, T=$T"
				if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
					sed -i -e "s#set \$fn=.*#set \$fn=fs$f$T$i#g" $f
				fi
				sudo filebench -f $f > $RESULTS/$f/$T\_$i
			done

			# In some(!) cases this is redundant yes... But these two workloads really require
			# the disk to be formatted between every single run with Bento....
			if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
				# These workloads are wobly, so
				cd ..
				./umount
				./prepare_disk
				./mount
				cd filebenches
			fi
		done
	else
		for i in $(seq 1 $REPS); do
			echo "i=$i"
			sudo filebench -f $f > $RESULTS/$f/$i
		done
	fi
done
