#!/bin/bash

cd filebenches

RESULTS=$MNT/results/filebench
sudo mkdir -p $MNT/results/filebench

TSET=( 18 1 )
REPS=10

sudo sh -c 'echo 0 > /proc/sys/kernel/randomize_va_space'

for f in *.f; do
	# These workloads are wobly, so
	../umount
	../prepare_disk
	../mount

	sed -i -e "s#set \$dir=.*#set \$dir=$MNT#g" $f
	echo "Running $f"
	sudo mkdir -p $RESULTS/$f

	if echo $f | grep "1t"; then
		for T in "${TSET[@]}"; do
			sed -i -e "s#set \$nthreads=.*#set \$nthreads=$T#g" $f

			WREPS=$REPS
			if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
				WREPS=1
			fi
			for i in $(seq 1 $WREPS); do
				echo "Iter: $i"
				if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
					sed -i -e "s#set \$fn=.*#set \$fn=fs$f$T$i#g" $f
				fi
				sudo sh -c "filebench -f $f > $RESULTS/$f/$T\_$i"
			done
		done
	else
		for i in $(seq 1 $REPS); do
			echo "Iter: $i"
			sudo sh -c "filebench -f $f > $RESULTS/$f/$i"
		done
	fi
done
