#!/bin/bash

cd filebenches

RESULTS=$MNT/results/filebench
sudo mkdir -p $MNT/results/filebench

TSET=( 18 1 )
REPS=10

sudo sh -c 'echo 0 > /proc/sys/kernel/randomize_va_space'

for f in *.f; do
	sed -i -e "s#set \$dir=.*#set \$dir=$MNT#g" $f
	echo "Running $f"
	sudo mkdir -p $RESULTS/$f

	if echo $f | grep "1t"; then
		for T in "${TSET[@]}"; do
			sed -i -e "s#set \$nthreads=.*#set \$nthreads=$T#g" $f
			for i in $(seq 1 $REPS); do
				sudo sh -c "filebench -f $f > $RESULTS/$f/$T\_$i"
			done
		done
	else
		for i in $(seq 1 $REPS); do
			sudo sh -c "filebench -f $f > $RESULTS/$f/$i"
		done
	fi

done
