#!/bin/bash


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ $FS == "Bento-fs" ]] || [[ $FS == "Bento-prov" ]]; then
	$SCRIPT_DIR/bento_mount_disk
elif [[ $FS == "Bento-user" ]]; then
	$SCRIPT_DIR/bento_mount_user
elif [[ $FS == "ext4-ordered" ]]; then
	$SCRIPT_DIR/ext4-o_mount_disk
elif [[ $FS == "ext4-journal" ]]; then
	$SCRIPT_DIR/ext4-j_mount_disk
fi
