#!/bin/bash

if [ $FS == "Bento-fs"] || [ $FS == "Bento-user" ] || [ $FS == "Bento-prov" ]; then
	./bento_prepare_disk
else if [ $FS == "ext4-ordered" ] || [ $FS == "ext4-journal" ]; then
	./ext4_prepare_disk
fi