#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ $FS == "Bento-fs" ]] || [[ $FS == "Bento-user" ]] || [[ $FS == "Bento-prov" ]]; then
	IMG=$SCRIPT_DIR/xv6fs.img
	if [ ! -f "$IMG" ]; then
		make -C $SCRIPT_DIR/bento/xv6fs/mkfs
		$SCRIPT_DIR/bento/xv6fs/mkfs/mkfs $IMG
	fi
	sudo dd if=$IMG of=$DISK bs=4096 status=progress

elif [[ $FS == "ext4-ordered" ]] || [[ $FS == "ext4-journal" ]]; then
	sudo mkfs.ext4 -F -F $DISK
fi
