#!/bin/bash

cd filebenches

RESULTS=../results/ram/$FS/filebench
mkdir -p $RESULTS

TSET=( 18 1 )
REPS=10

sudo sh -c 'echo 0 > /proc/sys/kernel/randomize_va_space'

reinit() {
	cd ..
	./umount
	if [ $FS == "Bento-fs" ] || [ $FS == "Bento-user" ]; then
		./bento_init
	elif [ $FS == "Bento-prov" ]; then
		./bento-prov_init
	fi
	./prepare_disk
	./mount
	cd filebenches
}

FSET=(  "seq_read_1t_128k" "seq_write_1t_128k" "rand_read_1t_128k" "rand_write_1t_128k" )

for f in "${FSET[@]}"; do
	# These workloads are wobly with Bento, so
	reinit

	sed -i -e "s#set \$dir=.*#set \$dir=$MNT#g" $f
	echo "Running $f"
	mkdir -p $RESULTS/$f

	if echo $f | grep "1t"; then
		for T in "${TSET[@]}"; do
			sed -i -e "s#set \$nthreads=.*#set \$nthreads=$T#g" $f

			WREPS=$REPS
			# These are bugged :(
			if [[ ( $FS == "Bento-fs" || $FS == "Bento-prov" ) && ( $f == "createfiles_1t.f" || $f == "deletefiles_1t.f" || $f == seq_write_1t_* ) ]]; then
				WREPS=1
			fi
			for i in $(seq 1 $WREPS); do
				echo "i=$i, T=$T"
				if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
					sed -i -e "s#set \$fn=.*#set \$fn=fs$f$T$i#g" $f
				fi
				sudo filebench -f $f > $RESULTS/$f/$T\_$i
			done

			# In some(!) cases this is redundant yes... But these two workloads really require
			# the disk to be formatted between every single run with Bento....
			if [ $f == "createfiles_1t.f" ] || [ $f == "deletefiles_1t.f" ]; then
				# These workloads are wobly, so
				reinit
			fi
		done
	else
		WREPS=$REPS
		if [[ ( $FS == "Bento-fs" || $FS == "Bento-prov" ) && $f == "webserver.f" ]]; then
			WREPS=4
		fi
		for i in $(seq 1 $WREPS); do
			echo "i=$i"
			sudo filebench -f $f > $RESULTS/$f/$i
		done
	fi
done

