#!/bin/bash

sudo mkdir $MNT/rocksdb_bench
sudo strace -f -t -e trace=file sudo ~/rocksdb/db_bench -benchmarks fillrandom,readrandom -num 1000000 -value_size 100 -wal_dir=$MNT --db=$MNT/rocksdb_bench -threads 8
