#!/bin/bash

if [ -z $DISK ]; then
	echo "You need to set \$DISK"
	exit
fi

FSL=( "Bento-fs" "Bento-user" "Bento-prov" "ext4-ordered" "ext4-journal")
for FS in "${FSL[@]}"; do
	export FS=$FS
	export MNT=/mnt/$FS

	./bento_init

	./prepare_disk
	./mount
	./redis
	./rocksdb
	./otherapps

	sudo cp -r $MNT/results ./results/$FS
	sudo find results -type d -exec chmod 755 {} \;
	sudo find results -type f -exec chmod 644 {} \;
	sudo find results -type f -exec chown -R $USER:$USER {} \;
	sudo find results -type d -exec chown -R $USER:$USER {} \;

	# filebench writes to the final results dir immediately
	./filebench

	./umount
done

FSL2=( "Bento-fs" "ext4-journal")
for FS in "${FSL2[@]}"; do
	export FS=$FS
	export MNT=/mnt/$FS

	./bento_init

	./prepare_disk
	./mount

	# writes to the final results dir immediately
	./fio_latency

	./umount
done
