#!/bin/bash

if [ -z $DISK ]; then
	echo "You need to set \$DISK"
	exit
fi

mkdir results
if [ "$(ls -A results)" ]; then
	echo "uuh results is not empty"
	exit
fi

FSL=( "Bento-fs" "Bento-user" "Bento-prov" "ext4-ordered" "ext4-journal")
for FS in "${FSL[@]}"; do
	export FS=$FS
	export MNT=/mnt/$FS

	if [ $FS == "Bento-fs" ] || [ $FS == "Bento-user" ]; then
		./bento_init
	elif [ $FS == "Bento-prov" ]; then
		./bento-prov_init
	fi

	./prepare_disk
	./mount
	./redis
	./rocksdb
	./otherapps
	./filebench

	sudo cp -r $MNT/results ./results/$FS
	sudo find results -type d -exec chmod 755 {} \;
	sudo find results -type f -exec chmod 644 {} \;
	sudo find results -type f -exec chown -R $USERNAME:$USERNAME {} \;
	sudo find results -type d -exec chown -R $USERNAME:$USERNAME {} \;
	./umount
done
