#!/bin/bash


export DISK=/dev/ram0
FSL3=( "ext4-journal" )
for FS in "${FSL3[@]}"; do
	export FS=$FS
	export MNT=/mnt/$FS

	sudo rmmod brd
	sudo modprobe brd rd_nr=1 rd_size=500000000

	./bento_init

	./prepare_disk
	./mount

	# writes to the final results dir immediately
	./filebench_ram

	./umount
done
