#!/bin/bash

sudo rmmod brd
sudo modprobe brd rd_nr=1 rd_size=500000000

export DISK=/dev/ram0
FSL3=( "Bento-fs" "ext4-journal")
for FS in "${FSL3[@]}"; do
	export FS=$FS
	export MNT=/mnt/$FS

	./bento_init

	./prepare_disk
	./mount

	# writes to the final results dir immediately
	./ram_filebench

	./umount
done
