#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
RESULTS=$SCRIPT_DIR/results
P=$RESULTS/processed.csv
mv $P $P\_old
touch $P

TSET=( 20 1 )
REPS=10

echo "workload; i; T; stat" | tee -a $P

for f in *.f; do
	for i in $(seq 1 $REPS); do
		REGEX=""
		if echo "$f" | grep -P "(create)|(delete)" > /dev/null; then
			REGEX='(?<=rd\/wr\s)\d*.\d*(?=mb\/s)'
		else
			REGEX='\d*.\d*(?=\sops\/s)'
		fi

		R=""
		if echo $f | grep "1t" > /dev/null; then
			for T in "${TSET[@]}"; do
				R=$(cat ${RESULTS}/${f}\_$T\_$i.out | grep -P -o ${REGEX} )
				echo "${f}; $i; $T; ${R}" | tee -a $P > /dev/null
			done
		else
			R=$(cat ${RESULTS}/${f}\_$i.out | grep -P -o ${REGEX} )
			echo "${f}; $i;; ${R}" | tee -a $P > /dev/null
		fi
	done
done
